server:
  port: ${PORT:8080}
  shutdown: graceful

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        generate_statistics: false

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 3000

feign:
  client:
    api:
      url: ${API_URL:https://api.twelvedata.com}
      key: ${API_KEY}

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 15000ms
        permittedNumberOfCallsInHalfOpenState: 3
        ignoreExceptions:
          - by.ares.transaction_validation_service.exception.ApiException
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1000ms
        retryExceptions:
          - by.ares.transaction_validation_service.exception.ApiTimeoutException
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 15

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false