spring:
  application:
    name: TransactionValidationService

  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        group:
          enabled: true

resilience4j:
  circuitbreaker:
    instances:
      currency-read-client:
        baseConfig: default
  retry:
    instances:
      currency-read-client:
        baseConfig: default
  bulkhead:
    instances:
      currency-read-client:
        baseConfig: default