server:
  port: 8080

spring:
  application:
    name: TransactionValidationService

  threads:
    virtual:
      enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jpa:
      properties:
        hibernate:
          show_sql: "true"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        group:
          enabled: true
feign:
  client:
    api:
      url: ${API_URL}

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      ignoreExceptions:
        - by.ares.transaction_validation_service.exception.ApiException
  instances:
    currency-read-client:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxAttempts: 5
      waitDuration: 500ms
      retryExceptions:
        - by.ares.transaction_validation_service.exception.ApiTimeoutException
  instances:
    currency-read-client:
      baseConfig: default

resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 5
  instances:
    currency-read-client:
      baseConfig: default